/**
 * Migration template generator
 *
 * @module @alexi/create/templates/unified/migration_ts
 */

/**
 * Generate migrations/0001_init.ts content
 */
export function generateInitMigration(name: string): string {
  return `/**
 * ${toPascalCase(name)} Initial Migration
 *
 * @module ${name}/migrations/0001_init
 */

// Placeholder for initial migration
// Migrations will be auto-generated by makemigrations
export const migration = {
  name: "0001_init",
  app: "${name}",
  operations: [],
};
`;
}

/**
 * Convert kebab-case to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}
